local tf = require('FoobarTests/lib/test_framework')
local mu = require('Foobar/lib/musicutil-extended')

tf.describe('musicutil extensions', function()
  tf.it('converts intervals to bits and back', function()
    local bits = mu.intervals_to_bits({0,4,7})
    tf.assert.are.equal(1| (1<<4) | (1<<7), bits)
    local ints = mu.bits_to_intervals(bits)
      tf.assert.are.same({0,4,7}, ints)
  end)

  tf.it('shifts scales', function()
    local s = mu.intervals_to_bits({0,2,4,5,7,9,11})
    local shifted = mu.shift_scale(s,2)
    tf.assert.is_number(shifted)
  end)
end)
